[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scilib"
version = "0.1.0"
description = "Precision scientific calculations"
dependencies = ["numpy"]
readme = "../../README.md"
